### ISSUE TITLE
Pytnon 3 Install

### ISSUE THREAD

**Issue by ssolson** [chrisspen/criticalpath#2]
Hey I see you attempted to make the code Python 3 compatible. The install works great for my Python 2 but in Python 3 I get the following error:

  Downloading criticalpath-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-build-c7ksj_uf\criticalpath\setup.py", line 7, in <module>
        import criticalpath
      File "C:\Users\username\AppData\Local\Temp\pip-build-c7ksj_uf\criticalpath\criticalpath.py", line 337
        """.format(**dict(
          ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-build-c7ksj_uf\criticalpath\

**Comment by chrisspen** [comment]
This has been fixed in the latest release.
