### ISSUE TITLE
how to change Node's duration?

### ISSUE THREAD

**Issue by sq6jnx** [chrisspen/criticalpath#4]
Hello, @chrisspen ,

I'd like to perform some kind of "what-if" analysis with cripticalpath.

For start let's assume, that example graph from project example has all nodes duration set to 2:

```
from criticalpath import Node
p = Node('project')
a = p.add(Node('A', duration=2))
b = p.add(Node('B', duration=2))
c = p.add(Node('C', duration=2))
d = p.add(Node('D', duration=2))
e = p.add(Node('E', duration=2))
p.link(a, b).link(a, c).link(a, d).link(b, e).link(c, e).link(d, e)
p.update_all()
print(p.get_critical_path())
print(p.duration)
```

Critical path is A->C->E with duration of 6.

Now the what if part: How can I change single node's duration to, say 0, without the need of rebuilding whole graph? Is it possible?

I've tried `b.duration = 0` and `p.get_or_create_node('B').duration = 0`, but I get the following error:

```
Traceback (most recent call last):
  File "(...)/cpm.py", line 15, in <module>
    p.update_all()
  File "C(...)\lib\site-packages\criticalpath\criticalpath.py", line 375, in update_all
    self.es = path[0].es
TypeError: 'Node' object is not subscriptable
```

**Comment by chrisspen** [comment]
That's not currently supported, and I no longer maintain this project, since I don't personally use it. However, adding that functionality wouldn't be too complicated. You'd have to track which nodes have changed since the last `update_all()`, and then either modify `update_all()` or create a new `update_incremental()` that only updates starting from the nodes that have changed. After each node processed, it's children would then be marked as changed, and the loop repeated until no more nodes have changed.

That error you encountered is probably just a bug. I don't think I have any testing around updating nodes and then doing a batch update. A PR would be welcome.
